name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js (example)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies (if any)
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Run tests (if any)
        run: |
          if [ -f package.json ]; then npm test || true; fi